### ISSUE TITLE
Build works in Netlify but not locally

### ISSUE THREAD

**Issue by DavidWells** [netlify-labs/netlify-plugin-next#2]
There is an issue with running this plugin locally. The plugin fails with this error when run with `netlify build` locally:

```
┌─────────────────────────────┐
│     Core internal error     │
└─────────────────────────────┘

  Error message
  Error: Error

  Error location
      at normalizeError (/Users/davidwells/.nvm/versions/node/v12.7.0/lib/node_modules/netlify-cli/node_modules/@netlify/build/src/error/parse/parse.js:75:10)
      at parseErrorInfo (/Users/davidwells/.nvm/versions/node/v12.7.0/lib/node_modules/netlify-cli/node_modules/@netlify/build/src/error/parse/parse.js:50:70)
      at parseError (/Users/davidwells/.nvm/versions/node/v12.7.0/lib/node_modules/netlify-cli/node_modules/@netlify/build/src/error/parse/parse.js:26:7)
      at serializeLogError (/Users/davidwells/.nvm/versions/node/v12.7.0/lib/node_modules/netlify-cli/node_modules/@netlify/build/src/error/parse/serialize_log.js:7:94)
      at logBuildError (/Users/davidwells/.nvm/versions/node/v12.7.0/lib/node_modules/netlify-cli/node_modules/@netlify/build/src/log/main.js:250:72)
      at build (/Users/davidwells/.nvm/versions/node/v12.7.0/lib/node_modules/netlify-cli/node_modules/@netlify/build/src/core/main.js:119:5)
      at async BuildCommand.run (/Users/davidwells/.nvm/versions/node/v12.7.0/lib/node_modules/netlify-cli/src/commands/build/index.js:16:25)
      at async BuildCommand._run (/Users/davidwells/.nvm/versions/node/v12.7.0/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:43:20)

```

The working remote logs can be seen here [Remote build logs](https://app.netlify.com/sites/next-netlify-plugin/deploys/5f162ce85b789a0008e1c716)

Any ideas what is happening here @ehmicky ?

To reproduce, clone down this repo, install the deps for site and run `netlify build` locally.

**Comment by DavidWells** [comment]
I managed to fix this. Paths are different from locally using plugin vs remotely using due to `@netlify` namespace. https://github.com/netlify-labs/netlify-plugin-next/commit/e2076e7fa51bfa261140db34364b2fa7a41d8746

The error is being swallowed though 
![image](https://user-images.githubusercontent.com/532272/87998057-aaae7600-caab-11ea-9e20-2fa263746555.png)

Will file bug in build repo
